"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";

import { api, ApiError } from "@/lib/client/api";
import { useDeployments } from "@/lib/client/deployments-store";
import { fixed, int } from "@/lib/format";
import { THERMAL } from "@/lib/thermal";
import type {
  DeploymentProfile,
  FlagSchema,
  FlagSpec,
  VramEstimate,
} from "@/lib/types";
import { buildServeArgv, formatCommand, parseServeCommand, type FlagValue } from "@/lib/vllm/argv";
import { coerceFlagValue, essentialRank } from "@/lib/vllm/parse-help";
import { Button, Note, Panel, Problem, Readout } from "@/components/ui/primitives";

import { FlagField } from "./FlagField";

/**
 * The exhaustive deployment form.
 *
 * Every option the installed vLLM accepts is here, grouped exactly as vLLM's
 * own `--help=all` groups them, with an Essentials tier lifted to the top.
 * Two rules make that many controls usable:
 *
 *  1. An untouched option is *not sent*, so the form never silently pins a
 *     default that changes between vLLM versions.
 *  2. The command preview is generated by the same builder the supervisor
 *     spawns, so what is on screen is exactly what will run.
 */
export function DeploymentForm() {
  const router = useRouter();
  const params = useSearchParams();
  const { live, refresh, setProjection } = useDeployments();

  const [schema, setSchema] = useState<FlagSchema | null>(null);
  const [schemaError, setSchemaError] = useState<string | null>(null);
  const [loadingSchema, setLoadingSchema] = useState(true);

  const [name, setName] = useState("");
  const [model, setModel] = useState(params.get("model") ?? "");
  const [servedName, setServedName] = useState("");
  const [port, setPort] = useState<string>("");
  // The models page hands over a chosen context length; seed it as initial
  // state rather than writing it from an effect after the first paint.
  const [flags, setFlags] = useState<Record<string, FlagValue>>(() => {
    const preset = params.get("max-model-len");
    const initial: Record<string, FlagValue> = {};
    if (preset) initial["max-model-len"] = preset;
    return initial;
  });
  const [profileId, setProfileId] = useState<number | null>(null);

  const [query, setQuery] = useState("");
  const [onlySet, setOnlySet] = useState(false);
  const [openGroups, setOpenGroups] = useState<Set<string>>(new Set());
  const [estimate, setEstimate] = useState<VramEstimate | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [conflict, setConflict] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [importing, setImporting] = useState(false);
  const [importText, setImportText] = useState("");

  /* --- schema ----------------------------------------------------------- */

  const loadSchema = useCallback(async (refreshSchema = false) => {
    setLoadingSchema(true);
    setSchemaError(null);
    await Promise.resolve();
    try {
      const r = await api.get<{ schema: FlagSchema }>(
        `/api/flags${refreshSchema ? "?refresh=1" : ""}`,
      );
      setSchema(r.schema);
    } catch (e) {
      setSchemaError((e as Error).message);
    } finally {
      setLoadingSchema(false);
    }
  }, []);

  useEffect(() => {
    void Promise.resolve().then(() => loadSchema());
  }, [loadSchema]);

  /* --- prefill from a saved profile or the models page ------------------- */

  useEffect(() => {
    const id = params.get("profile");
    if (!id) return;
    api
      .get<{ profile: DeploymentProfile }>(`/api/deployments/${id}`)
      .then(({ profile }) => {
        setProfileId(profile.id);
        setName(profile.name);
        setModel(profile.model);
        setServedName(profile.servedName ?? "");
        setPort(profile.port ? String(profile.port) : "");
        setFlags(profile.flags as Record<string, FlagValue>);
      })
      .catch((e) => setError((e as Error).message));
  }, [params]);

  const specs = useMemo(() => {
    const m = new Map<string, FlagSpec>();
    for (const f of schema?.flags ?? []) m.set(f.name, f);
    return m;
  }, [schema]);

  /* --- validation ------------------------------------------------------- */

  const errors = useMemo(() => {
    const out: Record<string, string> = {};
    for (const [name, raw] of Object.entries(flags)) {
      const spec = specs.get(name);
      if (!spec) continue;
      const r = coerceFlagValue(spec, raw as string);
      if (!r.ok) out[name] = r.error;
    }
    return out;
  }, [flags, specs]);

  /** Flags coerced to their real types, ready to send. */
  const typedFlags = useMemo(() => {
    const out: Record<string, FlagValue> = {};
    for (const [name, raw] of Object.entries(flags)) {
      const spec = specs.get(name);
      if (!spec) {
        out[name] = raw;
        continue;
      }
      const r = coerceFlagValue(spec, raw as string);
      if (r.ok) out[name] = r.value;
    }
    return out;
  }, [flags, specs]);

  /* --- live VRAM projection --------------------------------------------- */

  useEffect(() => {
    const t = setTimeout(async () => {
      if (!model.trim()) {
        setEstimate(null);
        return;
      }
      try {
        const num = (k: string, d: number) => {
          const v = typedFlags[k];
          const n = typeof v === "number" ? v : Number.parseFloat(String(v ?? ""));
          return Number.isFinite(n) ? n : d;
        };
        const str = (k: string, d: string) =>
          typeof typedFlags[k] === "string" && typedFlags[k] ? String(typedFlags[k]) : d;

        const r = await api.post<{ estimate: VramEstimate }>("/api/vram", {
          model: model.trim(),
          maxModelLen: typedFlags["max-model-len"] ? num("max-model-len", 8192) : undefined,
          gpuMemoryUtilization: num("gpu-memory-utilization", 0.9),
          kvCacheDtype: str("kv-cache-dtype", "auto"),
          dtype: str("dtype", "auto"),
          tensorParallelSize: num("tensor-parallel-size", 1),
        });
        setEstimate(r.estimate);
      } catch {
        setEstimate(null);
      }
    }, 400);
    return () => clearTimeout(t);
  }, [model, typedFlags, setProjection]);

  // Ghost segment on the shell's headroom rail.
  useEffect(() => {
    if (estimate?.known) setProjection({ label: model || "new deployment", mib: estimate.totalGiB * 1024 });
    else setProjection(null);
    return () => setProjection(null);
  }, [estimate, model, setProjection]);

  /* --- command preview -------------------------------------------------- */

  const preview = useMemo(() => {
    if (!model.trim()) return "";
    const argv = buildServeArgv(
      {
        name: name || model,
        model: model.trim(),
        servedName: servedName.trim() || null,
        flags: typedFlags,
      },
      { host: "127.0.0.1", port: Number(port) || 8000 },
    );
    return formatCommand("vllm", argv);
  }, [model, name, servedName, port, typedFlags]);

  /* --- actions ---------------------------------------------------------- */

  const setFlag = useCallback((flagName: string, v: FlagValue | undefined) => {
    setFlags((f) => {
      const next = { ...f };
      if (v === undefined) delete next[flagName];
      else next[flagName] = v;
      return next;
    });
  }, []);

  const save = async () => {
    setBusy(true);
    setError(null);
    try {
      const body = {
        name: name.trim() || model.split("/").pop() || "deployment",
        model: model.trim(),
        servedName: servedName.trim() || null,
        port: port ? Number(port) : null,
        flags: typedFlags,
      };
      if (profileId) await api.patch(`/api/deployments/${profileId}`, body);
      else await api.post("/api/deployments", body);
      router.push("/deployments");
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  const start = async (force = false) => {
    setBusy(true);
    setError(null);
    setConflict(null);
    try {
      const { runId } = await api.post<{ runId: number }>("/api/deployments/start", {
        name: name.trim() || model.split("/").pop(),
        model: model.trim(),
        servedName: servedName.trim() || null,
        port: port ? Number(port) : null,
        flags: typedFlags,
        force,
      });
      refresh();
      router.push(`/deployments/${runId}`);
    } catch (e) {
      if (e instanceof ApiError && e.status === 409) setConflict(e.message);
      else setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  const importCommand = () => {
    const parsed = parseServeCommand(importText, specs);
    if (parsed.model) setModel(parsed.model);
    setFlags((f) => ({ ...f, ...(parsed.flags as Record<string, FlagValue>) }));
    setImporting(false);
    setImportText("");
    if (parsed.unknown.length > 0) {
      setError(
        `Imported, but this vLLM does not have: ${parsed.unknown.join(" ")}. Those were skipped.`,
      );
    }
  };

  /* --- filtered flag list ----------------------------------------------- */

  const visible = useMemo(() => {
    const q = query.trim().toLowerCase();
    return (schema?.flags ?? []).filter((f) => {
      if (onlySet && flags[f.name] === undefined) return false;
      if (!q) return true;
      return (
        f.name.includes(q) ||
        f.help.toLowerCase().includes(q) ||
        f.group.toLowerCase().includes(q) ||
        f.aliases.some((a) => a.includes(q))
      );
    });
  }, [schema, query, onlySet, flags]);

  // Ordered by how often an operator reaches for them, not alphabetically —
  // --max-model-len belongs above --api-key.
  const essentials = useMemo(
    () =>
      visible
        .filter((f) => f.essential)
        .sort((a, b) => essentialRank(a.name) - essentialRank(b.name)),
    [visible],
  );
  const byGroup = useMemo(() => {
    const m = new Map<string, FlagSpec[]>();
    for (const f of visible) {
      const list = m.get(f.group) ?? [];
      list.push(f);
      m.set(f.group, list);
    }
    return m;
  }, [visible]);

  const setCount = Object.keys(flags).length;
  const hasErrors = Object.keys(errors).length > 0;
  const searching = query.trim().length > 0 || onlySet;

  const toggleGroup = (g: string) =>
    setOpenGroups((s) => {
      const next = new Set(s);
      if (next.has(g)) next.delete(g);
      else next.add(g);
      return next;
    });

  return (
    <div className="grid grid-cols-1 xl:grid-cols-[1fr_400px] min-h-full">
      {/* ---------------- options ---------------- */}
      <div className="min-w-0 flex flex-col">
        {error && <Problem>{error}</Problem>}

        <Panel label={profileId ? "edit deployment" : "new deployment"} ticked>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 px-3 py-2.5 hairline-t">
            <label className="flex flex-col gap-1 col-span-2">
              <span className="plate">model — repo id or local path</span>
              <input
                value={model}
                onChange={(e) => setModel(e.target.value)}
                placeholder="ibm-granite/granite-4.1-8b"
                autoFocus
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="plate">name</span>
              <input
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder={model.split("/").pop() ?? "deployment"}
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="plate">served as</span>
              <input
                value={servedName}
                onChange={(e) => setServedName(e.target.value)}
                placeholder="what clients ask for"
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="plate">port</span>
              <input
                type="number"
                value={port}
                onChange={(e) => setPort(e.target.value)}
                placeholder="auto"
              />
            </label>
          </div>
        </Panel>

        {loadingSchema && (
          <p className="px-3 py-4 plate">
            reading options from vllm — this imports torch and takes a few seconds
          </p>
        )}

        {schemaError && (
          <div className="flex flex-col gap-2 p-3">
            <Problem>{schemaError}</Problem>
            <span className="flex gap-1">
              <Button onClick={() => loadSchema(true)}>retry</Button>
              <Link href="/settings">
                <Button tone="primary">open settings</Button>
              </Link>
            </span>
          </div>
        )}

        {schema && (
          <>
            <div className="flex items-center gap-2 px-3 py-2 hairline-t sticky top-0 bg-void z-10">
              <input
                type="search"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder={`Search ${schema.flags.length} options`}
                className="flex-1"
                aria-label="Search vLLM options"
              />
              <Button
                onClick={() => setOnlySet((v) => !v)}
                tone={onlySet ? "primary" : "default"}
              >
                set only · {setCount}
              </Button>
              <Button onClick={() => setImporting((v) => !v)}>import</Button>
            </div>

            {importing && (
              <div className="px-3 py-2 hairline-t flex flex-col gap-2">
                <span className="plate">paste a vllm serve command</span>
                <textarea
                  rows={3}
                  value={importText}
                  onChange={(e) => setImportText(e.target.value)}
                  placeholder="vllm serve org/model --max-model-len 16384 --gpu-memory-utilization 0.9"
                />
                <span className="flex gap-1">
                  <Button tone="primary" onClick={importCommand}>
                    import options
                  </Button>
                  <Button onClick={() => setImporting(false)}>cancel</Button>
                </span>
              </div>
            )}

            {!searching && essentials.length > 0 && (
              <Panel label="essentials">
                {essentials.map((f) => (
                  <FlagField
                    key={f.name}
                    spec={f}
                    value={flags[f.name]}
                    error={errors[f.name]}
                    onChange={(v) => setFlag(f.name, v)}
                  />
                ))}
              </Panel>
            )}

            {searching ? (
              <Panel label={`${visible.length} matching`}>
                {visible.length === 0 ? (
                  <p className="px-3 py-4 plate">nothing matches</p>
                ) : (
                  visible.map((f) => (
                    <FlagField
                      key={f.name}
                      spec={f}
                      value={flags[f.name]}
                      error={errors[f.name]}
                      onChange={(v) => setFlag(f.name, v)}
                    />
                  ))
                )}
              </Panel>
            ) : (
              <div className="flex flex-col">
                {schema.groups.map((g) => {
                  const list = byGroup.get(g) ?? [];
                  if (list.length === 0) return null;
                  const open = openGroups.has(g);
                  const setHere = list.filter((f) => flags[f.name] !== undefined).length;
                  return (
                    <section key={g}>
                      <button
                        onClick={() => toggleGroup(g)}
                        aria-expanded={open}
                        className="w-full flex items-center gap-3 px-3 h-8 hairline-t hover:bg-panel transition-colors text-left"
                      >
                        <span className="plate text-ink-dim">
                          {open ? "▾" : "▸"} {g}
                        </span>
                        <span className="flex-1 h-px bg-rule" />
                        {setHere > 0 && (
                          <span className="plate" style={{ color: "var(--color-signal)" }}>
                            {setHere} set
                          </span>
                        )}
                        <span className="plate">{list.length}</span>
                      </button>
                      {open &&
                        list.map((f) => (
                          <FlagField
                            key={f.name}
                            spec={f}
                            value={flags[f.name]}
                            error={errors[f.name]}
                            onChange={(v) => setFlag(f.name, v)}
                          />
                        ))}
                    </section>
                  );
                })}
              </div>
            )}
          </>
        )}
      </div>

      {/* ---------------- preview + actions ---------------- */}
      <aside className="xl:hairline-l min-w-0">
        <div className="xl:sticky xl:top-0 flex flex-col">
          <Panel label="command" ticked>
            {preview ? (
              <pre className="num text-[11px] leading-relaxed px-3 py-2 whitespace-pre-wrap break-all text-ink-dim overflow-auto max-h-72">
                {preview}
              </pre>
            ) : (
              <p className="px-3 py-3 plate">choose a model to see the command</p>
            )}
          </Panel>

          {estimate && (
            <Panel label="projected vram">
              <div className="px-3 py-2 flex flex-col gap-1.5">
                <div className="flex items-baseline gap-2">
                  <span
                    className="plate"
                    style={{
                      color: !estimate.known
                        ? THERMAL.t3
                        : estimate.fits
                          ? THERMAL.t2
                          : THERMAL.t4,
                    }}
                  >
                    {!estimate.known ? "cannot verify" : estimate.fits ? "fits" : "will not fit"}
                  </span>
                  <span className="num text-[13px]">{fixed(estimate.totalGiB, 1)}</span>
                  <span className="plate">
                    of {fixed(estimate.availableGiB, 1)} gib free
                  </span>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  <Readout label="weights" value={fixed(estimate.weightsGiB, 2)} size="sm" />
                  <Readout label="kv cache" value={fixed(estimate.kvAtContextGiB, 2)} size="sm" />
                  <Readout label="overhead" value={fixed(estimate.activationOverheadGiB, 2)} size="sm" />
                </div>
                {estimate.maxContextThatFits != null && (
                  <p className="plate">
                    max context that fits: {int(estimate.maxContextThatFits)}
                  </p>
                )}
                {estimate.notes.map((n) => (
                  <p key={n} className="text-[11px] text-ink-faint leading-snug">
                    {n}
                  </p>
                ))}
              </div>
            </Panel>
          )}

          {conflict && (
            <div className="p-3 flex flex-col gap-2">
              <Note>{conflict}</Note>
              <span className="flex gap-1">
                <Button tone="danger" onClick={() => start(true)} disabled={busy}>
                  start anyway
                </Button>
                <Button onClick={() => setConflict(null)}>go back</Button>
              </span>
            </div>
          )}

          <div className="flex flex-wrap gap-1 p-3 hairline-t">
            <Button
              tone="primary"
              onClick={() => start(false)}
              disabled={busy || !model.trim() || hasErrors}
            >
              {busy ? "starting" : "start now"}
            </Button>
            <Button onClick={save} disabled={busy || !model.trim() || hasErrors}>
              {profileId ? "save changes" : "save profile"}
            </Button>
            <Link href="/deployments">
              <Button>cancel</Button>
            </Link>
          </div>

          {hasErrors && (
            <Problem>
              {Object.keys(errors).length} option
              {Object.keys(errors).length === 1 ? " needs" : "s need"} a valid value:{" "}
              {Object.keys(errors)
                .map((k) => `--${k}`)
                .join(", ")}
            </Problem>
          )}

          {live.length > 0 && (
            <div className="px-3 py-2 hairline-t">
              <span className="plate">already running</span>
              <ul className="mt-1 flex flex-col gap-0.5">
                {live.map((d) => (
                  <li key={d.runId} className="text-[11px] text-ink-faint truncate">
                    {d.servedName ?? d.name} :{d.port}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </aside>
    </div>
  );
}
